# Copyright (c) 2026 ux-dom
"""``uxdom add`` — generate routes, components, and XElements in an app tree."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Literal, Optional


class AddError(RuntimeError):
    pass


def _ensure_route_packages(routes_root: Path, file_path: Path) -> None:
    """Create ``__init__.py`` for every package dir from routes_root → file parent."""
    routes_root = routes_root.resolve()
    parent = file_path.parent.resolve()
    try:
        rel = parent.relative_to(routes_root)
    except ValueError:
        return
    cur = routes_root
    for part in rel.parts:
        cur = cur / part
        init = cur / "__init__.py"
        if not init.exists():
            init.write_text("", encoding="utf-8")


def _find_app_root(start: Optional[Path] = None) -> Path:
    cur = (start or Path.cwd()).resolve()
    for p in [cur, *cur.parents]:
        if (p / "app" / "routes").is_dir() and (p / "app").is_dir():
            return p
        if p == p.parent:
            break
    raise AddError(
        "not inside a ux-dom app (expected app/routes/). "
        "Run from a project with app/routes/. Product page units: uxcompose create-app."
    )


def _class_name(name: str) -> str:
    parts = re.split(r"[^a-zA-Z0-9]+", name.strip())
    parts = [p for p in parts if p]
    if not parts:
        raise AddError("empty name")
    return "".join(p[:1].upper() + p[1:] for p in parts)


def _path_params_from_route_name(name: str) -> list[str]:
    """Extract ``[id]`` → id from a route path string."""
    return re.findall(r"\[([a-zA-Z_][a-zA-Z0-9_]*)\]", name)


def _module_stem(name: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9_]+", "_", name.strip()).strip("_").lower()
    if not s:
        raise AddError("empty name")
    if s[0].isdigit():
        s = "r_" + s
    return s


def add_component(
    name: str, *, root: Optional[Path] = None, force: bool = False
) -> Path:
    """Create ``app/components/{stem}.py`` with a Component stub."""
    app_root = _find_app_root(root)
    stem = _module_stem(name)
    cls = _class_name(name)
    path = app_root / "app" / "components" / f"{stem}.py"
    if path.exists() and not force:
        raise AddError(f"{path} exists (use --force)")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        f'''"""{cls} component — generated by ``uxdom add component``."""
from __future__ import annotations

from ux_dom import Component
from ux_dom.dom import div


class {cls}(Component):
    """Shared UI building block."""

    def render(self, *args, **kwargs):
        return div(*args, className="rounded-lg border border-slate-200 p-4", **kwargs)
''',
        encoding="utf-8",
    )
    return path


def add_route(
    name: str,
    *,
    root: Optional[Path] = None,
    force: bool = False,
    methods: str = "get",
) -> Path:
    """Create ``app/routes/...`` DirectoryRoutes page unit.

    * ``about`` → ``routes/about.py`` class ``About``
    * ``admin/dashboard`` → ``routes/admin/dashboard.py``
    * ``users/[id]`` → ``routes/users/[id]/route.py`` class ``Page``
      (``[id]`` → ``{{id}}``; Components in ``route.py`` supported)
    """
    if not name or not str(name).strip():
        raise AddError("empty name")

    app_root = _find_app_root(root)
    if "/" in name or "[" in name:
        parts = [p for p in name.strip("/").split("/") if p]
        last = parts[-1]
        if last.startswith("[") and last.endswith("]"):
            cls = "Page"
            dir_path = app_root / "app" / "routes" / Path(*parts)
            path = dir_path / "route.py"
        else:
            cls = _class_name(last)
            if len(parts) > 1:
                dir_path = app_root / "app" / "routes" / Path(*parts[:-1])
                path = dir_path / f"{_module_stem(last)}.py"
            else:
                path = app_root / "app" / "routes" / f"{_module_stem(last)}.py"
    else:
        stem = _module_stem(name)
        cls = _class_name(name)
        path = app_root / "app" / "routes" / f"{stem}.py"

    if path.exists() and not force:
        raise AddError(f"{path} exists (use --force)")
    path.parent.mkdir(parents=True, exist_ok=True)
    _ensure_route_packages(app_root / "app" / "routes", path)

    methods_list = [m.strip().lower() for m in methods.split(",") if m.strip()] or [
        "get"
    ]
    routes_lit = repr(methods_list)
    params = _path_params_from_route_name(name)
    if params:
        get_sig = "".join(f", {p}: str" for p in params)
        title_bits = ", ".join("{" + p + "}" for p in params)
        page_title_src = 'f"' + cls + " (" + title_bits + ')"'
    else:
        get_sig = ""
        page_title_src = f'"{cls}"'

    content = f'''"""{cls} route — generated by ``uxdom add route`` (pure-dom, not product scaffold).

DirectoryRoutes URL derives from this file path under app/routes/.
``[id]`` folders become ``{{id}}`` path params.
"""
from __future__ import annotations

from ux_dom import Component
from ux_dom.dom import a, div, h1, p

from app.document import page


class {cls}(Component):
    routes = {routes_lit}

    def render(self, *args, **kwargs):
        return div(
            a("← Home", href="/", className="text-sm text-sky-600"),
            h1("{cls}", className="text-2xl font-bold mt-4 mb-2"),
            p("Edit this file under app/routes/.", className="text-slate-600"),
            className="max-w-2xl mx-auto px-4 py-10",
        )

    @classmethod
    def get(cls{get_sig}):
        return page(cls(), page_title={page_title_src})
'''
    path.write_text(content, encoding="utf-8")
    return path


XKind = Literal["light", "shadow", "alpine"]


def add_xelement(
    name: str,
    *,
    kind: XKind = "light",
    root: Optional[Path] = None,
    force: bool = False,
) -> Path:
    """Create an XElement subclass under app/components/."""
    if not name or not str(name).strip():
        raise AddError("empty name")
    app_root = _find_app_root(root)
    stem = _module_stem(name)
    cls = _class_name(name)
    tag = stem.replace("_", "-")
    path = app_root / "app" / "components" / f"x_{stem}.py"
    if path.exists() and not force:
        raise AddError(f"{path} exists (use --force)")

    if kind == "light":
        extra_imp = "CustomElement"
        base = "CustomElement"
        body = f"""        return template(
            div(
                "{cls} (light DOM)",
                className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm",
            ),
            **{{"x-tagname": tag_name}},
        )"""
        note = "Light DOM — no shadowroot. Runtime: x_element.js"
    elif kind == "shadow":
        extra_imp = "WebComponent"
        base = "WebComponent"
        body = f"""        return template(
            div(
                slot(),
                className="rounded-xl bg-slate-900 text-slate-100 p-4 text-sm",
            ),
            **{{"x-tagname": tag_name, "shadowroot": "true"}},
        )"""
        note = "Shadow DOM — shadowroot required. Runtime: x_element.js"
    else:
        extra_imp = "AlpineComponent"
        base = "AlpineComponent"
        body = f"""        return template(
            div(
                "click me",
                className="cursor-pointer rounded-lg border px-3 py-2 text-sm",
                **{{
                    "x-data": "{{ on: false }}",
                    "@click": "on = !on",
                    "x-text": "on ? 'ON' : 'OFF'",
                }},
            ),
            **{{"x-tagname": tag_name}},
        )"""
        note = "Alpine + XElement — needs x-data and Alpine.js on the page"

    path.write_text(
        f'''"""{cls} XElement ({kind}) — generated by ``uxdom add xelement``.

{note}

Usage: {cls}() places a host. Definition is registry SSoT (auto-collected).
"""
from __future__ import annotations

from dataclasses import dataclass

from ux_dom.dom import div, slot, template
from ux_dom.dom.htmlelement import {extra_imp}


@dataclass(eq=False)
class {cls}({base}):
    tag_name = "{tag}"

    def render(self, tag_name: str = "{tag}"):
{body}
''',
        encoding="utf-8",
    )
    return path
