# Copyright (c) 2026 ux-dom
"""``uxdom add`` — generate routes, components, and XElements in an app tree."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Literal, Optional


class AddError(RuntimeError):
    pass


def _ensure_route_packages(routes_root: Path, file_path: Path) -> None:
    """Create ``__init__.py`` for every package dir from routes_root → file parent."""
    routes_root = routes_root.resolve()
    parent = file_path.parent.resolve()
    try:
        rel = parent.relative_to(routes_root)
    except ValueError:
        return
    cur = routes_root
    for part in rel.parts:
        cur = cur / part
        init = cur / "__init__.py"
        if not init.exists():
            init.write_text("", encoding="utf-8")


def _find_app_root(start: Optional[Path] = None) -> Path:
    cur = (start or Path.cwd()).resolve()
    for p in [cur, *cur.parents]:
        if (p / "app" / "routes").is_dir() and (p / "app").is_dir():
            return p
        if p == p.parent:
            break
    raise AddError(
        "not inside a ux-dom app (expected app/routes/). "
        "Run from a project with app/routes/. Product page units: uxcompose create-app."
    )


def _class_name(name: str) -> str:
    parts = re.split(r"[^a-zA-Z0-9]+", name.strip())
    parts = [p for p in parts if p]
    if not parts:
        raise AddError("empty name")
    return "".join(p[:1].upper() + p[1:] for p in parts)


def _path_params_from_route_name(name: str) -> list[str]:
    """Extract ``[id]`` → id from a route path string."""
    return re.findall(r"\[([a-zA-Z_][a-zA-Z0-9_]*)\]", name)


def _module_stem(name: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9_]+", "_", name.strip()).strip("_").lower()
    if not s:
        raise AddError("empty name")
    if s[0].isdigit():
        s = "r_" + s
    return s


def add_component(
    name: str, *, root: Optional[Path] = None, force: bool = False
) -> Path:
    """Create ``app/components/{stem}.py`` with a Component stub."""
    app_root = _find_app_root(root)
    stem = _module_stem(name)
    cls = _class_name(name)
    path = app_root / "app" / "components" / f"{stem}.py"
    if path.exists() and not force:
        raise AddError(f"{path} exists (use --force)")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        f'''"""{cls} component — generated by ``uxdom add component``."""
from __future__ import annotations

from ux_dom.dom import div
from ux_dom.dom.htmlelement import Component


class {cls}(Component):
    def render(self, *args, **kwargs):
        return div("{cls}", className="p-4")
'''
        ,
        encoding="utf-8",
    )
    return path


def add_route(
    name: str,
    *,
    root: Optional[Path] = None,
    force: bool = False,
    page_title: Optional[str] = None,
) -> Path:
    """Create a DirectoryRoutes-compatible page unit under app/routes/.

    Path law: stem-only URLs. ``[id]`` segments become path params on ``get``.
    """
    app_root = _find_app_root(root)
    # Normalize name to path segments; keep [param] syntax
    raw = name.strip().strip("/")
    if not raw:
        raise AddError("empty name")
    # File path: replace [id] with id for filesystem, keep original for routes list
    file_parts = []
    route_parts = []
    for seg in raw.split("/"):
        if not seg:
            continue
        m = re.fullmatch(r"\[([a-zA-Z_][a-zA-Z0-9_]*)\]", seg)
        if m:
            file_parts.append(m.group(1))
            route_parts.append(seg)
        else:
            file_parts.append(_module_stem(seg) if seg != "index" else "index")
            route_parts.append(seg if seg != "index" else "")
    # index → routes/index.py maps to /
    if file_parts == ["index"]:
        rel = Path("index.py")
        routes_lit = '["/"]'
        cls = "Index"
        get_sig = ""
        page_title_src = repr(page_title or "Home")
    else:
        # last segment is the module
        *dirs, last = file_parts
        rel = Path(*dirs) / f"{last}.py" if dirs else Path(f"{last}.py")
        # routes list: rebuild URL from route_parts (empty → /)
        url = "/" + "/".join(p for p in route_parts if p)
        if not url.endswith("/") and last == "index":
            url = url.rstrip("/") or "/"
        routes_lit = repr([url or "/"])
        cls = _class_name(last if last != "index" else (dirs[-1] if dirs else "Index"))
        params = _path_params_from_route_name("/" + "/".join(route_parts))
        if params:
            get_sig = ", " + ", ".join(f"{p}: str" for p in params)
        else:
            get_sig = ""
        page_title_src = repr(page_title or cls)

    path = app_root / "app" / "routes" / rel
    if path.exists() and not force:
        raise AddError(f"{path} exists (use --force)")
    path.parent.mkdir(parents=True, exist_ok=True)
    _ensure_route_packages(app_root / "app" / "routes", path)

    content = f'''"""{cls} page — generated by ``uxdom add route``."""
from __future__ import annotations

from ux_dom.dom import a, div, h1, p
from ux_dom.dom.htmlelement import Component

from app.document import page


class {cls}(Component):
    routes = {routes_lit}

    def render(self, *args, **kwargs):
        return div(
            a("← Home", href="/", className="text-sm text-sky-600"),
            h1("{cls}", className="text-2xl font-bold mt-4 mb-2"),
            p("Edit this file under app/routes/.", className="text-slate-600"),
            className="max-w-2xl mx-auto px-4 py-10",
        )

    @classmethod
    def get(cls{get_sig}):
        # Path params are positional/keyword by name (never **kwargs)
        return page(cls(), page_title={page_title_src})
'''
    path.write_text(content, encoding="utf-8")
    return path


XKind = Literal["light", "shadow", "alpine"]


def add_xelement(
    name: str,
    *,
    kind: XKind = "light",
    root: Optional[Path] = None,
    force: bool = False,
) -> Path:
    """Create an XElement subclass under app/components/."""
    if not name or not str(name).strip():
        raise AddError("empty name")
    app_root = _find_app_root(root)
    stem = _module_stem(name)
    cls = _class_name(name)
    path = app_root / "app" / "components" / f"{stem}.py"
    if path.exists() and not force:
        raise AddError(f"{path} exists (use --force)")
    path.parent.mkdir(parents=True, exist_ok=True)

    if kind == "light":
        body = f'''"""{cls} XElement (light) — generated by ``uxdom add xelement``."""
from __future__ import annotations

from ux_dom.dom import div
from ux_dom.dom.htmlelement import XElement


class {cls}(XElement):
    tag = "{stem.replace("_", "-")}"

    def render(self, *args, **kwargs):
        return div(f"{cls} light", className="p-2 border rounded")
'''
    elif kind == "shadow":
        body = f'''"""{cls} XElement (shadow) — generated by ``uxdom add xelement"."""
from __future__ import annotations

from ux_dom.dom import div
from ux_dom.dom.htmlelement import XElement


class {cls}(XElement):
    tag = "{stem.replace("_", "-")}"
    shadow = True

    def render(self, *args, **kwargs):
        return div(f"{cls} shadow", className="p-2 border rounded")
'''
    else:  # alpine
        body = f'''"""{cls} XElement (alpine) — generated by ``uxdom add xelement"."""
from __future__ import annotations

from ux_dom.dom import div
from ux_dom.dom.htmlelement import XElement


class {cls}(XElement):
    tag = "{stem.replace("_", "-")}"

    def render(self, *args, **kwargs):
        return div(
            f"{cls} alpine",
            **{{"x-data": "{{ open: false }}"}},
            className="p-2 border rounded",
        )
'''
    path.write_text(body, encoding="utf-8")
    return path
